### ISSUE TITLE
Set project in all cloud calls

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#112]
If the project is not set via gcloud, the logs are spammed with messages like this:
[WARNING] No project ID could be determined from the Cloud SDK configuration. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable

This is probably because there is some cloud library that is being initialized without the project name.  We should make sure these all have the project set explicitly, and this should also clear up these errors.

**Comment by berggren** [comment]
This is probably not in Turbinia. This comes from module _default.py in function _get_gcloud_sdk_credentials. It happens if we set project correctly in the call. We are pinning 0.26  because of breaking changes so it is possible that this is fixed in newer versions of the cloud library.

We should fix and upgrade.

**Comment by berggren** [comment]
Probably related to #96

**Comment by aarontp** [comment]
I'm pretty sure this was fixed by updating the libraries and suppressing some other warnings.  Closing this for now.
