### ISSUE TITLE
High load causes inaccurate run times and early timeouts

### ISSUE THREAD

**Issue by jleaniz** [google/turbinia#1198]
Based on some testing, it seems the Turbinia server will close and fail tasks that are not completed within the specified job timeout, even if no worker picked up the tasks for execution.

This is evident in cases where we have more tasks than workers (since a worker only picks up one task at a time). I tested an environment with 10 workers and 826 tasks. Tasks started to timeout after a while because the 10 workers were busy and not picking up the rest of the tasks.

Ideally, jobs will only timeout iff a) a worker has started executing the task, and b) the execution time exceeds the configured timeout. Currently only (b) is a necessary condition for a job timeout.

**Comment by wajihyassine** [comment]
Related to the issue chatted with you about @aarontp when was doing the node autoscaling. Need to come up with a better way for server side timeouts but temp fix so far was to also just increase job timeouts to something super high.

**Comment by aarontp** [comment]
Here are a few options as I see it:

1) We could calculate the task time on the server based on when the task is actually picked up by the worker instead of when it is created, but one issue with that is that if the worker fails before it can update datastore, or for some reason the task never gets scheduled, then the task will hang indefinitely on the server side.  That doesn't happen too often anymore though, so this would definitely be an improvement.   Note that worker/task crashes or other failures in updating datastore are basically the reason that the server side timeouts exist (see the recent yara bug for example).

2) Now that we're (almost) using celery only, we could rely on the celery status instead of the status in datastore to calculate the task run time on the server.  This has a similar problem to #1 where tasks that crash before they can update Redis or never start will indefinitely hang on the server, but this is probably much less of a real issue since the celery code is realistically more stable than the Turbinia Task code.

3) Have one time out using option #1 or #2 (most likely #2), but have a second timeout value that is  calculated similar to today (the clock starts when the Task is created), but the timeout value is much higher to account for the queuing times (e.g. add a full day or more to every Task timeout value or something).

I think #3 is probably the best option, but we could also implement #1 as a quick fix.  #2 could potentially be a quick fix, but I'm not sure if the celery task stub is easily available when we are calculating the timeouts, so it might be a bit more plumbing work.

**Comment by wajihyassine** [comment]
Marking this as fixed per https://github.com/google/turbinia/pull/1215 + not seeing this as an issue from recent load tests 

Using a combination of options above increasing server time buffer and calculating the run_time from the worker itself seemed to do the trick. We have defaulted the server to only do a server side timeout if it reaching past a day + default Task timeout and the Worker will timeout based on the timeout time specified in job config. Having a user specific timeout from Web UI can be a nice to have for the future, can file a separate issue to track that one
