### ISSUE TITLE
Error when worker version doesn't match server

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#307]
We'll have to add version info to TurbiniaTask so that workers can reject tasks when there is a mis-match between the versions used by the server and the workers.  Strange errors can occur when the workers are running a different version from the server.

**Comment by fpiedrah** [comment]
@aarontp Hi! I'll want to take this task. Let me ask a couple of things first:

1) We need a version in `workers.TurbiniaTask` should this version be `turbinia.__version__`?
2) This version could be just an attribute inside `workers.TurbiniaTask` class?
3) This task requires to create the code inside the workers in order to reject the requests that have version mis-match?

Just making sure I'm in the right track before start making code.

**Comment by aarontp** [comment]
@fpiedrah Great, thanks much!

1. Yes, `turbinia.__version__` should be the common version referenced by all components.
2. Yes, that sounds good.
3. Also Yes: I think it should probably happen somewhere near the start of the `TurbiniaTask.run_wrapper()`.  Note that for the error to propagate back to the server, it will need to be returned as part of the `TurbiniaTaskResult()`, so it should happen after the result is created, but before the `TurbiniaTask.run()` method is called.  It would be good if the self.result.status also indicated the error (so it shows up in the client output).

I think clarifying and communicating on this before you started was a good idea, so thanks for doing that, :).
