### ISSUE TITLE
PUBSUB_TOPIC unclear

### ISSUE THREAD

**Issue by jgrover** [google/turbinia#369]
In the docs, one of the instructions states:

> Match the PUBSUB_TOPIC variable in the configuration to the name of the topic and subscription you created in the GCP.

The topic and subscription names created in GCP are two different values.  Which one do I use for the PUBSUB_TOPIC?  The topic name?  Or the subscription name?

**Comment by aarontp** [comment]
@jgrover thanks for the report.  The `PUBSUB_TOPIC` should actually be set to the topic name (just the part after `topics/` in the full topic path).   I think part of why the docs are incorrectly conflating the two here is that if you let Turbinia create the subscription, it will actually create it with the same path ending (e.g. the part after `subscriptions/`) as is set in the topic, so it refers to both of them being the same.  I'll keep this open to clean that up in the docs (they're due for a big refactoring, so I'm happy to get your reports/feedback).

**Comment by jgrover** [comment]
Thank you!  That clears it up.

**Comment by aarontp** [comment]
I'll keep this open for now just so I don't forget to update the docs.

@jgrover: Also, just FYI, there is another documentation pull request pending that includes a few more details on "local" installation (I know this issue is about the GCP setup, but I saw in the other Issues that you were also trying a local install): https://github.com/google/turbinia/pull/345 .   There was just one last question on that, and I can probably merge it soon.

One other note:  Feel free to join the Turbinia channel in the open-source DFIR slack, and we can also help with any issues that might come up:
https://github.com/open-source-dfir/slack

Thanks again for the reports!

**Comment by aarontp** [comment]
Fixed in https://github.com/google/turbinia/commit/2020cf9c11bc9f548efbdbc6f5c9af1b70d81395#diff-64407d3e6d5ef382426bdfbcae040c6a
