### ISSUE TITLE
Move YAPF checks to separate CI integration

### ISSUE THREAD

**Issue by joachimmetz** [google/turbinia#408]
The issue with the yapf test is that its results will depend on the version of yapf used. Consider removing the test and have a separate CI yapf test.

**Comment by aarontp** [comment]
@joachimmetz  How does moving it to a separate CI test fix the problem of YAPF versions?  We could also pin the version of YAPF in the dev dependencies if we really want to do that.  I agree it is a little annoying to have tests fail in Travis when they succeed locally, but no matter where we pin the version and what we pin it to, I think this will be an issue. 

One somewhat ugly option would be to run it with the last few (2-3?) versions and if any of them pass, then the overall test passes.  This would at least reduce the churn/pain.

One reason I like having YAPF as a project test is that it makes breakages more obvious to the developer during development time instead of finding out after creating the PR, seeing the CI errors, and then having to do another commit to fix things.

**Comment by joachimmetz** [comment]
So the issue is that every dev environment that wants to run the test needs to have the same version of yapf. By moving it to a separate CI test, this limitation goes away. Worst case you as the maintainer can run yapf the right version of yapf on the PR before merge

**Comment by aarontp** [comment]
I'm going to close this issue out as this hasn't been a problem in practice since the issue was filed.  If it starts being a pain we can re-open.
