### ISSUE TITLE
Graceful exit when starting multiple workers on same host

### ISSUE THREAD

**Issue by cteodor** [google/turbinia#452]
I just started looking through the source code so maybe I'm not getting this right.
**My scenario:** multiple workers taking plaso jobs, local scenario. What I want is to move the workers to containers and get tasks to work on from a Redis service.
**Problem:** While trying to start multiple workers (same machine or distinct) , as soon as a second worker starts (turbiniactl celeryworker) the 1st one balks with a kombu exception:
Cannot route message for exchange 'reply.celery.pidbix': Table empty or key no longer exists.
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.

**Steps:**
(console1) turbiniactl -S server 
(console2) turbiniactl celeryworker
(console3) turbiniactl celeryworker > 1st instance throws kombu exception

Is this a valid usage scenario? Any hints where to look at?

**Comment by aarontp** [comment]
Sorry for the delayed response, I was out for a bit.    Huh, that's a strange error.  You should definitely be able to start multiple workers, at least on different machines.  I don't suggest running the same worker on the same machine unless it's in a separate VM (not 100% about just separate containers since that's not tested yet) since the pre-processors will potentially cause conflicts with each other (e.g. by operating on the same resource), but if the resources are isolated, I think it should be OK.

@ericzinnikas any thoughts on the redis/celery side?

**Comment by aarontp** [comment]
BTW, if your use case is to run multiple containers per host, it would be interesting to talk more about what you're trying to achieve.  We have so far focused mostly on parallelizing machines/VMs because most of the Task types will take up all of a given type of resources on a given host (e.g. Plaso will spawn a process for every CPU, and other Tasks will end up maxing out IO).

**Comment by aarontp** [comment]
I'm going to change this bug to track a more graceful exit when starting multiple workers on the same host and using local Celery.  If there are other problems that need to be addressed with this, let me know.

**Comment by cteodor** [comment]
I wanted to run plaso jobs as parallel containers (in the meantime had a poc with Apache Airflow). 
Can be closed.
