### ISSUE TITLE
Configuration file not behaving as expected

### ISSUE THREAD

**Issue by tomchop** [google/turbinia#600]
I was struggling a bit today with having the configuration file mapped to what I needed it to be (for launching dftimewolf with a one-off configuration of Turbinia).

My ~/.turbiniarc is set to what I want, but the config is still picked up from "whatever file it can find" in the directory pointed to by `TURBINIA_CONFIG_PATH` (specified in `ENVCONFIGVAR`)

This happens because when importing `evidence` (e.g. `from turbinia import evidence`), `LoadConfig` is called with no parameters, and thus populates the config with whatever files it can find there. Subsequent calls to `LoadConfig`, even when passing a `config_file` will still return this first configuration because it has already been loaded.

**Comment by hacktobeer** [comment]
We could consider *always* loading the configuration if ```LoadConfig``` is called with the ```config_file``` parameter set (even if we already have a ```CONFIG``` initialized). This would behave how I would expect it (I think) -> I change the config file on disk, call ```LoadConfig```, it should update my config.
Change in below location to cover a check if the ```config_file``` param is set and force (re)load the configuration instead of returning the global one.
https://github.com/google/turbinia/blob/master/turbinia/config/__init__.py#L112
