### ISSUE TITLE
loop devices not being processed properly

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#778]
https://github.com/google/turbinia/runs/2011775885?check_suite_focus=true#step:9:1452
~~When a task is finished the raw disk gets detached from the loop device through ```losetup -d```.Which is fine in case of a raw disk but gets problematic in case of dealing with partitions.~~

```
2021-03-02 09:20:44 [INFO] Starting post-processor for evidence /evidence/artifact_disk.dd
2021-03-02 09:20:44 [INFO] Running: sudo losetup -d /dev/loop8
2021-03-02 09:20:44 [INFO] Running: sudo losetup -a
2021-03-02 09:20:44 [INFO] losetup device [/dev/loop8] deleted.
```

~~So the above task has detached the raw disk from the loop device.The next task will try to use the partition information available on the disk (which was on /dev/loop8) and will try to access the partition (see offsets below) from that /dev/loop8 device.But it can't as an earlier task has already detached the raw disk.~~

```
2021-03-02 09:20:44 [INFO] Starting Task BinaryExtractorTask 5ff706160e754c1aa12490c308ebf871
2021-03-02 09:20:44 [INFO] Running command sudo losetup --show --find -r /evidence/artifact_disk.dd
2021-03-02 09:20:44 [INFO] Running command sudo losetup --show --find -r -o 1048576 --sizelimit 19905536 /dev/loop8
losetup: /dev/loop8: failed to set up loop device: No such file or directory
Error: -02 09:20:45 [ERROR] Error running preprocessor for DiskPartition: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-r', '-o', '1048576', '--sizelimit', '19905536', '/dev/loop8']' returned non-zero exit status 1.
Error: -02 09:20:45 [ERROR] BinaryExtractorTask Task failed with exception: [Evidence DiskPartition:DiskPartition:None being processed by Task BinaryExtractorTask requires Evidence to be in state ATTACHED, but earlier pre-processors may have failed.  Current state is [MOUNTED: False, ATTACHED: False, DECOMPRESSED: False]. See previous logs for more information.]
```

**Comment by hacktobeer** [comment]
Going to test this outside of the github actions runner to see what is going on.

**Comment by hacktobeer** [comment]
This is something else, initial issue report is incorrect. Need to debug deeper to find root cause.

**Comment by aarontp** [comment]
Yeah, I'm seeing something similar, but I'm not sure if it's related.  It seems like `losetup` is failing on the initial pre-processing of the evidence.  For yours I see the error "losetup: /dev/loop8: failed to set up loop device: No such file or directory", which because it failed, it never went into an "ATTACHED" state, which will cause that later stack trace about a state mismatch.  

The error I'm seeing is similar (losetup complaining of the device not existing).  Note that for me this is within the VS code container after updating to include the change to start it as privileged.    The error message here seems misleading though because the path does exist.
```
2021-03-02 21:12:26 [INFO] Starting Task PartitionEnumerationTask ceb9590c1a7a4d1d95f2fd066afd7e3f
2021-03-02 21:12:26 [INFO] Running command sudo losetup --show --find -r /evidence/test-small.img
losetup: /evidence/test-small.img: failed to set up loop device: No such file or directory
2021-03-02 21:12:27 [ERROR] Error running preprocessor for /evidence/test-small.img: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-r', '/evidence/test-small.img']' returned non-zero exit status 1.

root@44aa80dbec5c:/workspaces/turbinia# losetup -v --show --find -r /evidence/test-small.img
losetup: /evidence/test-small.img: failed to set up loop device: No such file or directory

root@44aa80dbec5c:/workspaces/turbinia# ls -al /evidence/test-small.img
-rw-r----- 1 130500 89939 104857600 Dec  8 07:36 /evidence/test-small.img
```

If I run that same command on the host, it seems to run just fine, and sets up a loop device as expected.  I think it's possible that my container still isn't set up quite correctly though.  I now see `/dev/loop-control` and lots of other devices, but I don't see the actual /dev/loop{N} devices.

Is it possible that we're hitting the same misleading error (which looks like the source doesn't exist, but it's actually the destination loop device that doesn't exist), but for different reasons?  Your example ends with trying to create a new loop device from /dev/loop8 (to attach the partition instead of the root device).  Maybe `/dev/loop8` (or `/dev/loop7`) is the last configured loop device in your container, and it just needs new devices created?  And then maybe mine is failing because no other /dev/loopN devices exist at all.

One outstanding question even if that is the case though -- Why does your run start at /dev/loop8 and not /dev/loop0?  Is that just because it's a shared resource and the others are already taken?


FWIW, this appears to be the right code for losetup:  https://github.com/karelzak/util-linux/blob/master/sys-utils/losetup.c .  It seems like it should actually have a different error if there is not an unused loop device, but I've only skimmed through it.

**Comment by aarontp** [comment]
FWIW, I rebooted my machine because I had a udev rule that was changing permissions on loop devices to my user, and after removing that everything seemed to work fine from my container with respect to the loop devices being setup/deleted.

I still wonder if you had maybe run out of available loop devices as well during your run.  I'm not sure how resources like that are managed in the github containers.  Maybe there's something we need to reset?

**Comment by aarontp** [comment]
FYI, I was able replicate a similar failure by assigning all of my loop devices, and then I got the following error:
```
2021-03-03 05:29:41 [INFO] Running command sudo losetup --show --find -r /evidence/test-small.img
2021-03-03 05:29:41 [INFO] Running command sudo losetup --show --find -r /dev/loop7
losetup: /dev/loop7: failed to set up loop device: No such file or directory
2021-03-03 05:29:42 [ERROR] Error running preprocessor for DiskPartition: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-r', '/dev/loop7']' returned non-zero exit status 1.
```

**Comment by hacktobeer** [comment]
I did some more testing last night at home and it is an error message that's confusing. The first command should throw an error that there are no more free devices available. I'll have a look today at why it would start at loop8....which it should not.

**Comment by hacktobeer** [comment]
Welcome in the wonderful world of Ubuntu using snap packages :(.
```
Show loop device availability in worker
/dev/loop1: [2049]:59705 (/var/lib/snapd/snaps/core18_1988.snap)
/dev/loop8: [2049]:134897 (/var/lib/snapd/snaps/snapd_11107.snap)
/dev/loop4: [2049]:22319 (/var/lib/snapd/snaps/gtk-common-themes_1514.snap)
/dev/loop2: [2049]:60299 (/var/lib/snapd/snaps/chromium_1497.snap)
/dev/loop0: [2049]:70599 (/var/lib/snapd/snaps/core18_1944.snap)
/dev/loop7: [2049]:59698 (/var/lib/snapd/snaps/snapd_11036.snap)
/dev/loop5: [2049]:70598 (/var/lib/snapd/snaps/lxd_19188.snap)
/dev/loop3: [2049]:60302 (/var/lib/snapd/snaps/gnome-3-28-1804_145.snap)
```

**Comment by hacktobeer** [comment]
Getting a bit closer. 
```
2021-03-03 08:12:15 [INFO] Running command sudo losetup --show --find -r /evidence/artifact_disk.dd
losetup: /evidence/artifact_disk.dd: failed to set up loop device: No such file or directory
Error: -03 08:12:15 [ERROR] Error running preprocessor for /evidence/artifact_disk.dd: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-r', '/evidence/artifact_disk.dd']' returned non-zero exit status 1.
2021-03-03 08:12:15 [INFO] Running command sudo losetup --show --find -r -o 1048576 --sizelimit 19905536 /dev/loop7
losetup: /dev/loop7: failed to set up loop device: No such file or directory
Error: -03 08:12:16 [ERROR] Error running preprocessor for DiskPartition: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-r', '-o', '1048576', '--sizelimit', '19905536', '/dev/loop7']' returned non-zero exit status 1.
```

This seems to indicate something else. As if it can't find the evidence path.

**Comment by hacktobeer** [comment]
Narrowed it down to the DockerEnumerationJob. Disabling that makes the e2e (and all task) succeed. Did not have time today to look at it more, will continue tomorrow.
https://github.com/google/turbinia/runs/2023186790?check_suite_focus=true

**Comment by aarontp** [comment]
@hacktobeer Are we still seeing this issue?  There's been a few changes to how the preprocessors work for some of these evidence types since then, and I haven't seen this particular error recently.  LMK if we can close this.

**Comment by hacktobeer** [comment]
Nope, this issue is not showing anymore. Will close.
