### ISSUE TITLE
googleclouddisk job fails with multiple workers on same GCE host.

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#849]
When running multiple (dockerized) workers on the same GCE host the googleclouddisk job will fail with the error message "RESOURCE_IN_USE_BY_ANOTHER_RESOURCE".

The issue is that when a worker on a GCE host tries to mount the disk the first time it will succeed and expose the disk through the mapped /dev/ system into the first worker container. It fails when a second worker on the same GCE host tries to mount the disk as it's already mounted to that GCE host by the first worker.

The error is confusing, it's in use by the same resource, not by another resource.

**Comment by hacktobeer** [comment]
So we attach the disk, execute a task and detach the disk. 

We can check if a disk is already attached to the instance just before trying to attach it:
https://github.com/google/turbinia/blob/a3a2d6cf3d52f2af4def189d9e6a0369648e916f/turbinia/processors/google_cloud.py#L104

How do we handle detaching?
The issue becomes more complicated as we also detach the disk when the task ends. This can result in 1 worker detaching a disk from the GCE instance while another worker running on that same GCE instance is still using the disk!

**Comment by hacktobeer** [comment]
We can write a state file to GCS on attach and check if we have >1 statefile left on detach. Something like below.

On Attach:
```
# check if disk is already attached
cloudstorage.open(config.GCS_OUTPUT+'/state/'+diskname+'/'+instancename)
if NotFoundError:
   cloudstorage.open(config.GCS_OUTPUT+'/state/'+diskname+'/'+instancename, mode='w')
   AttachDisk()
```
On Detach:
```
files=cloudstorage.listbucket(config.GCS_OUTPUT+'/state/'+diskname)
if len(files) == 1:
  DetachDisk()
  cloudstorage.delete(config.GCS_OUTPUT+'/state/'+diskname+'/'+instancename)
else:
  cloudstorage.delete(config.GCS_OUTPUT+'/state/'+diskname+'/'+instancename)
```

**Comment by hacktobeer** [comment]
My first thought was to just catch the error and continue when the AttachDisk() returns an error that the disk is already attach. But that does not solve the issue of detaching so we need to share state anyway across workers around mounted evidence anyway.

**Comment by wajihyassine** [comment]
I think this approach makes sense and would work as a fix until we get some sort of API server going. I am also wondering/should probably test out how this effects pods on different nodes and whether they would be able to access the GCEPersistentDisk? Maybe that's a separate issue then the mounting process itself, but I know one potential solution is to make Volume Persistent Claims via Kubernetes which would allow all pods across all nodes access to the same GCEPersistentDisk: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by hacktobeer** [comment]
Different nodes can always attach GCE volumes as they are attached read
only. We don't have to use Volume Persistent Claimes. We only have an issue
with attaching the same disk to the same node (aka GCE instance) multiple
times.

**Comment by wajihyassine** [comment]
Ohh got it, perfect then. I feel like the approach you mentioned above would work then. I guess this goes against de - coupling GCE resources since using GCS, but maybe this can be a feature only enabled for GKE given that we'll be using GCPs managed instance of GKE anyways. The only other idea that comes to mind right now is doing a check before the GCE disk is mounted and not to mount if it already has been mounted, especially if we can reference a disk name or mount path. But I think this approach will run into issues when the disk needs to be unmounted at the end of the task run.

**Comment by hacktobeer** [comment]
Yeah, the detaching is the issue and that is why we need to keep track of
the attached state of a disk on a node. If it was only the attach part it
would be as easy as checking if /dev/disk/by-id/[disk-name] already exists
before attempting an AttachDisk() as shown below:
https://github.com/google/turbinia/blob/master/turbinia/processors/google_cloud.py#L90

Regarding de de-GCP-ing -> the job googleclouddisk (and the embedded
job) needs to be able to attach/detach a cloud disk so that's the only
place we can't not use GCP functionality.

**Comment by wajihyassine** [comment]
Yeah that makes sense on both ends, I think the only other best method really would be an API server then else this would be a good solution. Seems like we can also achieve something similar with datastore, but not sure what the added benefit of that would be over writing to GCS.

**Comment by wajihyassine** [comment]
Chatting with @aarontp around this as well, would it make more sense to instead have a local file on machine to check for since this is on a pod/node level? I guess the only downside is we have to mount an additional path with write access

**Comment by hacktobeer** [comment]
Yep,would love that. We could mount /tmp or /var/run from the node to the
pod.

This way we can have basic local paths to the state file which will
translate well to eg NFS paths in the lab.

Good idea!

**Comment by aarontp** [comment]
A few thoughts / ideas here:
- Another option could be instead of a directory of files, we could use a single locked resource state file (pickled or json) that has a counter per unique resource name (e.g. disk name) that gets incremented or decremented as resources are used or freed.   A variation of this might be to map the resource name to a list of the task IDs that are using the resource so that things could be more easily cleaned up in the case of a failure (since the task clean-up that happens during a failure wouldn't have to worry about decrementing the counter more than once).   This might make it a little easier to lock the entire resource tracking state to avoid race conditions.
- I agree with the above comments about the resources here being all local, so I think tracking the state and usage locally only should be just fine as well (no need for central tracking).
- This could apply to other evidence types as well (anything we have to "attach" to the host, possibly raw disks, and AWS disks in the future) so it would be nice if we could have an attribute (`reusable`? `singleton`?) that is set per evidence object and then if that attribute is set, then the pre and post processors can either update the resource state tracker or run the processor if it is the first or last use of that resource.  Then all we have to do is set that attribute for new evidence types to be handled as a singleton.
- Using a temporary directory that gets wiped on node restart is probably better than using shared storage so we don't have to worry about clean-up when things restart.

**Comment by wajihyassine** [comment]
Hi @hacktobeer to keep you updated, was taking a deeper look at this, so TLDR, we're going for an implementation that takes into account all types of `Evidence` that can run into the mounting issue (e.g. `RawDisk` , `GoogleCloudDisk`). I had some implementation ideas and after chatting some more with @aarontp going towards doing the following:

* Per Evidence type that needs to be tracked in state file, save all relevant paths of that `Evidence` type into the state file so that another `Task` trying to process same disk can have access to all necessary paths since attributes such as `mount_path` are only available when `Evidence` runs through preprocessor mounts. 
* Thinking something along the line of this:
  `resource_state = {$resource_id: {paths: {"source_path": "foo", "local_path": "bar"}
                                                     tasks: [$taskID1, $taskID2]}}`
* The `resource_id` will be used to check if it's same `Evidence` type and would be generated by combining multiple properties of `Evidence` type for example, `GoogleCloudDisk` can be generated with zone + disk name. If you think of a better way of generating a unique id that can be regenerated per worker, lmk
* In `Evidence.preprocess` add some logic that calls another method to check statefile for `resource_id` and if there is a match, pull associated paths and append `task_id` to it (will need to send this into the `Evidence` object) else run through `preprocess` code.
* In `Evidence.postprocess`, add some logic that checks for statefile and sees if there are +1 or more task_ids, if so remove the `task_id`, if it's the only `task_id` remaining, run through remove `task_id` and run through  `postprocess` code.

Please feel free to add any thoughts/comments!
