### ISSUE TITLE
Configure a remote VS Code devcontainer for GCP deployments

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#866]
We have the vs code devcontainers for local development, and it would be super cool if we could have something similar for debugging in GCP.  I'm not sure how that would intersect with our current deployment mechanisms, but it looks like it's possible to do: https://code.visualstudio.com/docs/remote/containers-tutorial

**Comment by wajihyassine** [comment]
So in order to have a setup in GCP environment, will need access to a project and to create a development VM (found that Ubuntu as the base os works best).

Once that is set up, using vscode, SSH into the GCE VM, some instructions here: https://cloud.google.com/compute/docs/instances/ssh

Once SSH into GCE VM, follow the exact steps in [develop-vscode.md](https://github.com/google/turbinia/blob/master/docs/developer/develop-vscode.md) docs but skip Step 4 and go to Step 5 - GCP hybrid Turbinia setup. 

The config file will also have to be updated post set up to SHARED_FILESYSTEM=False to allow turbiniactl to accept google cloud images.

Once done, you should be able to spin up a server/worker and send a request to process a googleclouddisk which allows for googleclouddisk to process.

Also this [PR](https://github.com/google/turbinia/pull/972) exposes /dev path for googleclouddisk to be seen by pod

**Comment by wajihyassine** [comment]
Also run `gcloud compute config-ssh` to setup gcloud ssh

**Comment by jleaniz** [comment]
@wajihyassine Looks like we can close this as completed?

**Comment by wajihyassine** [comment]
Yes this should still work although probably makes sense to have a GKE equivalent so that in realtime can help debug a few of those race condition issues we've been seeing. Will mark this as closed and we can open another issue to track that work
