### ISSUE TITLE
Request status does not show worker for all tasks

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#907]
All request status output should show the worker the task was execute on. 

Task examples:
```
# Successful Tasks
* WindowsAccountAnalysisTask: No Windows account files found
* LinuxAccountAnalysisTask: No weak passwords found
* PartitionEnumerationTask: Found 2 partition(s) in [evidence-test-disk-20210924075128-3b90aa9e-copy]:
* SSHDAnalysisTask: No issues found in SSH configuration
* WordpressCredsAnalysisTask: No weak passwords found
* JenkinsAnalysisTask: No Jenkins instance found
```

**Comment by aarontp** [comment]
I suggest we add a flag for this (or possibly just show this extra information when `-a` is specified) in order to keep the output clean  since the majority of the time we don't care which worker the task was executed on as long as it was successful.  Note that there is also a separate status view that groups Tasks by worker if you specify `turbiniactl status -w`.

**Comment by aarontp** [comment]
Actually, this information shows up if you add the `-R -p100` flag.  Is that good enough for this one?  I don't think we likely want to print it at all times, but we could potentially still make it a little easier to get.

**Comment by aarontp** [comment]
This data now shows up in the report by default.  Closing this out.
