### ISSUE TITLE
Create a FLS Job

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#959]
Create a job for FLS sleuthkit to timeline a given filesystem. Note that some filesystems such as XFS may not work so ensure that the Evidence type has a filter to targeted OS types

**Comment by tomchop** [comment]
Could we achieve performances similar to FLS using plaso with a very narrow set of parsers? @joachimmetz

**Comment by joachimmetz** [comment]
achieve what precisely? creating a bodyfile of allocated file entries?

**Comment by aarontp** [comment]
@joachimmetz  : Yes, just a basic file stat listing that results in a Timesketch importable file/timeline.  I don't know that script specifically, but between that, fls and just calling something like `log2timeline.py --parsers filestat`, which do you think would be better?

**Comment by joachimmetz** [comment]
"Better" here is a matter of trade offs

* So `log2timeline.py --parsers filestat` still does a lot of other stuff, such as hashing
* `fls` has numerous [known issues](https://github.com/sleuthkit/sleuthkit/issues?q=is%3Aissue+is%3Aopen+fls), [some](https://github.com/sleuthkit/sleuthkit/issues/2467) directly impacting processing time, others the accuracy of results, lack XFS support, seconds precision, etc.
* We could use different tools like `fsxfsinfo -H -B bodyfile image.raw` but that would require more logic in the Turbinia job
* Extending  https://github.com/open-source-dfir/dfvfs-snippets/blob/main/scripts/list_file_entries.py (or equiv) to create a bodyfile would (1) make the script take care of partition and volume systems instead of the job (2) add XFS support and other back-ends addressing various shortcomings in fls (3) have variable date and time precision depending on the file system

Should be relatively straight forward to extend the script. I can take a look when time permits

**Comment by joachimmetz** [comment]
Needs some cleaning up and fine tuning but basic functionality is implemented in https://github.com/log2timeline/imagetools/pull/7

Also works on an image with multiple partitions and volumes (e.g. LVM), might need some tweaking to make sure those are captured in the paths displayed

**Comment by jleaniz** [comment]
Thanks @joachimmetz - I will look into integrating the script with Turbinia as a new job.

**Comment by joachimmetz** [comment]
FYI it is not fully completed yet, some things it does not support. Give me a couple of days with the necessary uninterrupted time and I can put a test version into the GIFT PPA.

**Comment by joachimmetz** [comment]
First version is in GIFT PPA dev, it requires some dependencies still in pre-release

**Comment by wajihyassine** [comment]
Thanks for taking a look @joachimmetz ! Didn't realize the tradeoffs either so makes sense going this route. Just a qq that came to mind now around l2tl hashing. Is every file by default being hashed/can also be affecting performance significantly? If so, would it be possible to limit hashing to a subset of directories?

**Comment by joachimmetz** [comment]
You could process the image using a collection filter file with hashing. Plaso currently does not support selective hashing, with the exception files with data streams that exceed `--hasher-file-size-limit`
