### ISSUE TITLE
Log or correlate node names

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#973]
Now that we are using GKE with scaling, the nodes go up and down frequently, which leaves large amounts of log files that are easily attributed to the pod, but it's not easy to see what node those pods were running on after they have been turned down which can make debugging difficult.  We should find a way to log the node name in addition to the pod name or find a way to correlate those after the fact.  It's possible there is a simple kubectl command that can do this as well.

**Comment by aarontp** [comment]
FYI @wajihyassine

**Comment by wajihyassine** [comment]
Some thoughts on how we can expose/correlate the node name to the logging is
* Updating the environment variable of K8s deployment script to somehow pass the node name as an environment variable to the pod for turbinia to read. This environment variable will only be available however for kubernetes setups.
* Mount `/etc/hostname` path from node and read that file instead to grab node name. For non k8s environment, this would be redundant to calling uname.nodename
* When logger.setup is being initialized, append pod name into text file stored in the path `TMP_RESOURCE_DIR` and create new variable like `RESOURCE_POD_LIST` noting the file name. This fix may be the most straightforward since not having to retrieve the node name + add that into logging but we'd just need to SSH into a node + grep for pod name to do the correlation

**Comment by hacktobeer** [comment]
Add below to the worker and server pod yaml configuration files and afaik
with that the nodenane will be available in the pod as an environment
variable.
```
env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

**Comment by wajihyassine** [comment]
Thanks for the suggestion @hacktobeer. I was working on a PR related to logging (ready for review) and went ahead and updated it to also take into account node name per above.
